int leerEnteroPositivo(char*);
int leerEntero(char*);
int leerEnteroEntre(char*, int, int);
int leerEnteroMayor(char*, int);
int leerEnteroMenor(char*, int);
float leerFlotantePositivo(char*);
float leerFlotanteEntre(char*, float, float);
float leerFlotante(char*);
float leerFlotanteMayor(char*, float);
float leerFlotanteMenor(char*, float);
char leerChar(char*);